### ISSUE TITLE
Application Not Showing Lock

### ISSUE THREAD

**Issue by karopass** [mattsilber/applock#3]
Hello sir ! I have implemented Your Library. Application some time loading My Next Activity without showing lock for enter pin or for create PIN. I am facing issue in Android 6.0.1 with OnePlus3 Mobile. My Code is like below. What Should I do for solve the issue ?

`
public class LockActivity extends AppCompatActivity {
    /**
     * Whether or not the system UI should be auto-hidden after
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        final String PREFS_NAME = "MyPrefsFile";
        SharedPreferences settings = getSharedPreferences(PREFS_NAME, 0);
        if (settings.getBoolean("my_first_time", true)) {
            new CreateLockDialogBuilder(this,
                    new LockCreationListener(){
                        public void onLockCanceled(){ } // Dialog was closed without entry
                        public void onLockSuccessful(){
                            Intent intent = new Intent(LockActivity.this, ShowContentActivity.class);
                            startActivity(intent);
                        }
                    })
                    .show();
            settings.edit().putBoolean("my_first_time", false).commit();
        }
    }

    @Override
    protected void onStart() {
        super.onStart();
        ActionLockingHelper.unlockIfRequired(this, new UnlockEventListener(){
                public void onCanceled(){ } // Dialog was closed without entry
                public void onUnlockFailed(String reason){ } // Not called with default Dialog, instead is handled internally
                public void onUnlockSuccessful(){
                    Intent intent = new Intent(LockActivity.this, ShowContentActivity.class);
                    startActivity(intent);
                }
            });

    }
`

**Comment by mattsilber** [comment]
The problem is that the call to create the PIN and the call to unlock are both asynchronous, but they are being run at basically the same time in your code and, since a PIN won't yet exist by the time onStart() is called, it will validate as if it were unlocked.

Try moving the onStart()'s ActionLockingHelper.unlockIfRequired() call to your onCreate() method, and separate with an else:

    if (settings.getBoolean("my_first_time", true)) {
        new CreateLockDialogBuilder(this,....
    }
    else 
        ActionLockingHelper.unlockIfRequired(this,....

A side note: you probably don't want to save the "my_first_time" flag unless they successfully enter a PIN, so I would suggest moving that into the creation's onLockSuccessful() callback to avoid future bugs.
